In [2]:
import pandas as pd
rna = pd.read_table('ATF4_Publicdata/GSE76771_ALL_gene_expression.txt', header=4)
rna

/scratch/268655.1.ood/ipykernel_4172455/1025199513.py:2: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  rna = pd.read_table('ATF4_Publicdata/GSE76771_ALL_gene_expression.txt', header=4)

,test_id,gene_id,gene,locus,sample_1,sample_2,status,value_1,value_2,Value 3,Value 4,log2(fold_change),test_stat,p_value,q_value,significant,Unnamed: 16
0,XLOC_000001,XLOC_000001,Mrpl15,chr1:4763266-4776053,q1,q2,OK,37.431800,22.2465,27.238000,21.3535,-0.750685,-0.99303,0.08845,0.233153,no,NaN
1,XLOC_000002,XLOC_000002,Lypla1,chr1:4797973-4836816,q1,q2,OK,129.649000,60.7268,93.617800,56.7086,-1.0942,-3.21376,0.00005,0.000396,yes,NaN
2,XLOC_000003,XLOC_000003,Tcea1,chr1:4847774-4887990,q1,q2,OK,11.403900,35.5800,8.405530,22.7315,1.64154,4.81123,0.00005,0.000396,yes,NaN
3,XLOC_000004,XLOC_000004,Atp6v1h,chr1:5073174-5152695,q1,q2,OK,43.760900,42.6246,37.858200,47.6802,-0.0379559,-0.113404,0.84135,0.933306,no,NaN
4,XLOC_000005,XLOC_000005,Oprk1,chr1:5578573-5596214,q1,q2,NOTEST,0.004171,0.0000,0.003107,0.0000,#NAME?,0,1.00000,1.000000,no,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162649,XLOC_027107,XLOC_027107,Gm20865,chrY_random:48242250-48243108,q3,q4,NOTEST,0.000000,0.0000,NaN,NaN,0,0,1.00000,1.000000,no,NaN
162650,XLOC_027108,XLOC_027108,Gm20747,chrY_random:48319177-48321522,q3,q4,NOTEST,0.000000,0.0000,NaN,NaN,0,0,1.00000,1.000000,no,NaN
162651,XLOC_027109,XLOC_027109,Ssty1,chrY_random:48388360-48390745,q3,q4,NOTEST,0.000000,0.0000,NaN,NaN,0,0,1.00000,1.000000,no,NaN
162652,XLOC_027110,XLOC_027110,Gm20823,chrY_random:50814753-50817087,q3,q4,NOTEST,0.000000,0.0000,NaN,NaN,0,0,1.00000,1.000000,no,NaN
162653,XLOC_027111,XLOC_027111,Gm20736,chrY_random:52063164-52089373,q3,q4,NOTEST,0.000000,0.0000,NaN,NaN,0,0,1.00000,1.000000,no,NaN

In [2]:
sig_rna = rna[rna['significant'] == 'yes']
sig_rna = sig_rna[sig_rna['gene']!= '']
sig_rna = sig_rna[sig_rna['gene']!= '-']
sig_rna

,test_id,gene_id,gene,locus,sample_1,sample_2,status,value_1,value_2,Value 3,Value 4,log2(fold_change),test_stat,p_value,q_value,significant,Unnamed: 16
1,XLOC_000002,XLOC_000002,Lypla1,chr1:4797973-4836816,q1,q2,OK,129.64900,60.72680,93.61780,56.7086,-1.0942,-3.21376,0.00005,0.000396,yes,NaN
2,XLOC_000003,XLOC_000003,Tcea1,chr1:4847774-4887990,q1,q2,OK,11.40390,35.58000,8.40553,22.7315,1.64154,4.81123,0.00005,0.000396,yes,NaN
5,XLOC_000006,XLOC_000006,Rb1cc1,chr1:6202274-6266498,q1,q2,OK,11.87730,24.00940,9.50791,18.6403,1.0154,2.98767,0.00005,0.000396,yes,NaN
8,XLOC_000009,XLOC_000009,Pcmtd1,chr1:7079000-7163709,q1,q2,OK,32.17730,19.94960,29.46680,18.4394,-0.689684,-2.0965,0.00015,0.001079,yes,NaN
9,XLOC_000010,XLOC_000010,Rrs1,chr1:9535488-9537536,q1,q2,OK,11.50620,24.09370,13.20510,25.4585,1.06625,2.99521,0.00005,0.000396,yes,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162406,XLOC_026864,XLOC_026864,"Mbtps2,Yy2",chrX:153985753-154036647,q3,q4,OK,3.46128,6.58956,NaN,NaN,0.928876,2.35238,0.00025,0.001706,yes,0.279619684
162410,XLOC_026868,XLOC_026868,Cdkl5,chrX:157205944-157432621,q3,q4,OK,1.12592,1.84242,NaN,NaN,0.710499,1.65925,0.00315,0.015562,yes,0.213881106
162426,XLOC_026884,XLOC_026884,Ofd1,chrX:162827964-162891234,q3,q4,OK,1.38635,3.54952,NaN,NaN,1.35633,2.60375,0.00010,0.000747,yes,0.408296741
162434,XLOC_026892,XLOC_026892,Prps2,chrX:163784264-163820675,q3,q4,OK,8.19667,4.08075,NaN,NaN,-1.0062,-2.65015,0.00005,0.000396,yes,-0.302897461
162438,XLOC_026896,XLOC_026896,Hccs,chrX:165749462-165758310,q3,q4,OK,8.07035,12.84400,NaN,NaN,0.670397,1.79676,0.00225,0.011651,yes,0.201807927

In [3]:
# Filter the rows where the 'gene' column contains 'Mar' or 'Sep'
date_genes = sig_rna[sig_rna['gene'].str.contains(r'\b(Mar|Sep)\b', na=False, regex=True)]

# Extract the 'gene' column as a list
date_gene_list = date_genes['gene'].tolist()

print(date_gene_list)

['2-Sep', '1-Mar', '9-Sep', '6-Mar', '2-Mar', '3-Mar', '5-Mar', '11-Sep', '8-Sep', '2-Sep', '1-Mar', '9-Sep', '6-Mar', '3-Mar', '5-Mar', '11-Sep', '2-Sep', '9-Mar', '8-Sep', '9-Sep', '2-Mar', '3-Mar', '5-Mar', '11-Sep', '8-Mar', '6-Mar', '11-Sep', '2-Sep', '9-Sep', '3-Mar', '5-Mar', '7-Mar', '11-Sep', '7-Sep']

/scratch/267523.1.ood/ipykernel_3695441/2628799386.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  date_genes = sig_rna[sig_rna['gene'].str.contains(r'\b(Mar|Sep)\b', na=False, regex=True)]

In [4]:
import pandas as pd

# Mapping of month abbreviations to full names
month_mapping = {
    'Mar': 'March','Sep': 'Sept'
}

# Function to rename genes
def rename_gene(gene_name):
    if isinstance(gene_name, str):
        parts = gene_name.split('-', 1)  # Split only on the first '-'
        if len(parts) == 2:
            number, month_abbr = parts
            month_full = month_mapping.get(month_abbr, month_abbr)  # Use the mapping or keep the abbreviation
            return f"{month_full}{number}"
    return gene_name  # Return the original name if not in the 'number-Month' format or if not a string

# Apply the function to the 'gene' column
sig_rna['gene'] = sig_rna['gene'].apply(rename_gene)

# Display the updated DataFrame
print(sig_rna)

            test_id      gene_id        gene                     locus  \
1       XLOC_000002  XLOC_000002      Lypla1      chr1:4797973-4836816
2       XLOC_000003  XLOC_000003       Tcea1      chr1:4847774-4887990
5       XLOC_000006  XLOC_000006      Rb1cc1      chr1:6202274-6266498
8       XLOC_000009  XLOC_000009      Pcmtd1      chr1:7079000-7163709
9       XLOC_000010  XLOC_000010        Rrs1      chr1:9535488-9537536
...             ...          ...         ...                       ...
162406  XLOC_026864  XLOC_026864  Mbtps2,Yy2  chrX:153985753-154036647
162410  XLOC_026868  XLOC_026868       Cdkl5  chrX:157205944-157432621
162426  XLOC_026884  XLOC_026884        Ofd1  chrX:162827964-162891234
162434  XLOC_026892  XLOC_026892       Prps2  chrX:163784264-163820675
162438  XLOC_026896  XLOC_026896        Hccs  chrX:165749462-165758310

       sample_1 sample_2 status    value_1   value_2   Value 3  Value 4  \
1            q1       q2     OK  129.64900  60.72680  93.61780  56.7086
2            q1       q2     OK   11.40390  35.58000   8.40553  22.7315
5            q1       q2     OK   11.87730  24.00940   9.50791  18.6403
8            q1       q2     OK   32.17730  19.94960  29.46680  18.4394
9            q1       q2     OK   11.50620  24.09370  13.20510  25.4585
...         ...      ...    ...        ...       ...       ...      ...
162406       q3       q4     OK    3.46128   6.58956       NaN      NaN
162410       q3       q4     OK    1.12592   1.84242       NaN      NaN
162426       q3       q4     OK    1.38635   3.54952       NaN      NaN
162434       q3       q4     OK    8.19667   4.08075       NaN      NaN
162438       q3       q4     OK    8.07035  12.84400       NaN      NaN

       log2(fold_change) test_stat  p_value   q_value significant  \
1                -1.0942  -3.21376  0.00005  0.000396         yes
2                1.64154   4.81123  0.00005  0.000396         yes
5                 1.0154   2.98767  0.00005  0.000396         yes
8              -0.689684   -2.0965  0.00015  0.001079         yes
9                1.06625   2.99521  0.00005  0.000396         yes
...                  ...       ...      ...       ...         ...
162406          0.928876   2.35238  0.00025  0.001706         yes
162410          0.710499   1.65925  0.00315  0.015562         yes
162426           1.35633   2.60375  0.00010  0.000747         yes
162434           -1.0062  -2.65015  0.00005  0.000396         yes
162438          0.670397   1.79676  0.00225  0.011651         yes

         Unnamed: 16
1                NaN
2                NaN
5                NaN
8                NaN
9                NaN
...              ...
162406   0.279619684
162410   0.213881106
162426   0.408296741
162434  -0.302897461
162438   0.201807927

[21338 rows x 17 columns]

In [28]:
# Filter the DataFrame for rows where 'sample_1' is 'q1' and 'sample_2' is 'q2'
filtered_df = sig_rna[(sig_rna['sample_1'] == 'q1') & (sig_rna['sample_2'] == 'q4')]

filtered_df

,test_id,gene_id,gene,locus,sample_1,sample_2,status,value_1,value_2,Value 3,Value 4,log2(fold_change),test_stat,p_value,q_value,significant,Unnamed: 16
81328,XLOC_000002,XLOC_000002,Lypla1,chr1:4797973-4836816,q1,q4,OK,129.64900,56.70860,NaN,NaN,-1.19297,-3.48236,0.00005,0.000396,yes,NaN
81329,XLOC_000003,XLOC_000003,Tcea1,chr1:4847774-4887990,q1,q4,OK,11.40390,22.73150,NaN,NaN,0.995162,2.89273,0.00005,0.000396,yes,NaN
81332,XLOC_000006,XLOC_000006,Rb1cc1,chr1:6202274-6266498,q1,q4,OK,11.87730,18.64030,NaN,NaN,0.65022,1.92756,0.00080,0.004758,yes,NaN
81335,XLOC_000009,XLOC_000009,Pcmtd1,chr1:7079000-7163709,q1,q4,OK,32.17730,18.43940,NaN,NaN,-0.803253,-2.41504,0.00005,0.000396,yes,NaN
81336,XLOC_000010,XLOC_000010,Rrs1,chr1:9535488-9537536,q1,q4,OK,11.50620,25.45850,NaN,NaN,1.14574,3.21408,0.00005,0.000396,yes,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108197,XLOC_026873,XLOC_026873,Syap1,chrX:159294774-159326394,q1,q4,OK,44.80410,27.61840,NaN,NaN,-0.698003,-1.82861,0.00150,0.008223,yes,NaN
108202,XLOC_026878,XLOC_026878,Zrsr2,chrX:160373374-160414179,q1,q4,OK,2.90121,5.72310,NaN,NaN,0.980142,1.56519,0.01160,0.046835,yes,NaN
108208,XLOC_026884,XLOC_026884,Ofd1,chrX:162827964-162891234,q1,q4,OK,1.38742,3.54952,NaN,NaN,1.35522,2.70635,0.00005,0.000396,yes,NaN
108209,XLOC_026885,XLOC_026885,Rab9,chrX:162895183-162917799,q1,q4,OK,47.53730,31.56110,NaN,NaN,-0.590913,-1.70139,0.00305,0.015132,yes,NaN
108216,XLOC_026892,XLOC_026892,Prps2,chrX:163784264-163820675,q1,q4,OK,7.39545,4.08075,NaN,NaN,-0.857804,-2.21738,0.00010,0.000747,yes,NaN

In [29]:
# Remove entries with NaN in the 'gene' column
sig_rna_cleaned = filtered_df.dropna(subset=['gene'])

# Display the cleaned DataFrame
sig_rna_cleaned

,test_id,gene_id,gene,locus,sample_1,sample_2,status,value_1,value_2,Value 3,Value 4,log2(fold_change),test_stat,p_value,q_value,significant,Unnamed: 16
81328,XLOC_000002,XLOC_000002,Lypla1,chr1:4797973-4836816,q1,q4,OK,129.64900,56.70860,NaN,NaN,-1.19297,-3.48236,0.00005,0.000396,yes,NaN
81329,XLOC_000003,XLOC_000003,Tcea1,chr1:4847774-4887990,q1,q4,OK,11.40390,22.73150,NaN,NaN,0.995162,2.89273,0.00005,0.000396,yes,NaN
81332,XLOC_000006,XLOC_000006,Rb1cc1,chr1:6202274-6266498,q1,q4,OK,11.87730,18.64030,NaN,NaN,0.65022,1.92756,0.00080,0.004758,yes,NaN
81335,XLOC_000009,XLOC_000009,Pcmtd1,chr1:7079000-7163709,q1,q4,OK,32.17730,18.43940,NaN,NaN,-0.803253,-2.41504,0.00005,0.000396,yes,NaN
81336,XLOC_000010,XLOC_000010,Rrs1,chr1:9535488-9537536,q1,q4,OK,11.50620,25.45850,NaN,NaN,1.14574,3.21408,0.00005,0.000396,yes,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108197,XLOC_026873,XLOC_026873,Syap1,chrX:159294774-159326394,q1,q4,OK,44.80410,27.61840,NaN,NaN,-0.698003,-1.82861,0.00150,0.008223,yes,NaN
108202,XLOC_026878,XLOC_026878,Zrsr2,chrX:160373374-160414179,q1,q4,OK,2.90121,5.72310,NaN,NaN,0.980142,1.56519,0.01160,0.046835,yes,NaN
108208,XLOC_026884,XLOC_026884,Ofd1,chrX:162827964-162891234,q1,q4,OK,1.38742,3.54952,NaN,NaN,1.35522,2.70635,0.00005,0.000396,yes,NaN
108209,XLOC_026885,XLOC_026885,Rab9,chrX:162895183-162917799,q1,q4,OK,47.53730,31.56110,NaN,NaN,-0.590913,-1.70139,0.00305,0.015132,yes,NaN
108216,XLOC_026892,XLOC_026892,Prps2,chrX:163784264-163820675,q1,q4,OK,7.39545,4.08075,NaN,NaN,-0.857804,-2.21738,0.00010,0.000747,yes,NaN

In [30]:
sig_rna_cleaned['gene']

81328     Lypla1
81329      Tcea1
81332     Rb1cc1
81335     Pcmtd1
81336       Rrs1
           ...
108197     Syap1
108202     Zrsr2
108208      Ofd1
108209      Rab9
108216     Prps2
Name: gene, Length: 5036, dtype: object

In [9]:
atf4_isr = pd.read_table('Treatment/ATF4/results/annotation/ATF4_ISR_annotated.txt')
atf4_isr['SYMBOL']

0      A830018L16Rik
1            Gm17644
2            Gm17644
3             Arid5a
4           Mettl21e
           ...
322    G530011O06Rik
323    G530011O06Rik
324           Erdr1x
325           Erdr1x
326           Erdr1x
Name: SYMBOL, Length: 327, dtype: object

In [4]:
genes_to_check = sig_rna_cleaned['gene'].tolist()
filtered_genes_new = atf4_isr[atf4_isr['SYMBOL'].isin(sig_rna_cleaned['gene'])]
filtered_genes_new

NameError: name 'sig_rna_cleaned' is not defined

In [20]:
# Assuming your DataFrame is named 'atf4_isr'

# Drop the first row
atf4_isr_cleaned = filtered_genes_new.drop(filtered_genes_new.index[0])

# Display the cleaned DataFrame
print(atf4_isr_cleaned)

    seqnames      start        end  width strand                 V4   V5 V6  \
27     chr10   59788682   59788719     38      *  ATF4_ISR_peak_255   42  .
86     chr13   92146091   92146179     89      *  ATF4_ISR_peak_377  159  .
94     chr14   55777565   55777621     57      *  ATF4_ISR_peak_431   44  .
135    chr19   15902492   15902540     49      *  ATF4_ISR_peak_571   47  .
136    chr19   27194191   27194230     40      *  ATF4_ISR_peak_573   69  .
143    chr19   58470639   58470685     47      *  ATF4_ISR_peak_582  316  .
156     chr2  119181433  119181598    166      *  ATF4_ISR_peak_624  179  .
170     chr3   50398041   50398095     55      *  ATF4_ISR_peak_668   28  .
201     chr5   93437504   93437572     69      *  ATF4_ISR_peak_763  812  .
206     chr5  114311164  114311221     58      *  ATF4_ISR_peak_768  716  .
214     chr5  148356038  148356122     85      *  ATF4_ISR_peak_780  105  .
215     chr6    7693191    7693233     43      *  ATF4_ISR_peak_789   89  .
251     chr8   27751257   27751325     69      *  ATF4_ISR_peak_856   60  .
262     chr8  122625261  122625408    148      *  ATF4_ISR_peak_873   66  .
267     chr9   69350512   69350550     39      *  ATF4_ISR_peak_903   98  .

           V7        V8  ...  geneStart    geneEnd geneLength  geneStrand  \
27    6.19749   8.83817  ...   59785491   59787656       2166           2
86   11.77860  21.01310  ...   92001506   92025004      23499           2
94    6.26331   9.03793  ...   55777723   55787474       9752           1
135   6.44745   9.36532  ...   15882042   15902423      20382           2
136   7.55192  11.67470  ...   27194420   27212256      17837           1
143  18.30510  36.96510  ...   58441784   58444341       2558           2
156  11.61380  23.01790  ...  119181710  119184862       3153           1
170   5.39310   7.39269  ...   49846975   50398063     551089           2
201  35.63560  87.90390  ...   93416567   93421344       4778           1
206  33.14000  78.00470  ...  114313967  114328399      14433           1
214   9.34704  15.38320  ...  148264220  148336714      72495           2
215   8.46638  13.79060  ...    7675169    7693254      18086           2
251   7.10962  10.69900  ...   27750357   27766702      16346           1
262   7.41015  11.42460  ...  122615113  122623241       8129           2
267   9.04663  14.64410  ...   69360902   69399077      38176           1

     geneId           transcriptId  distanceToTSS             ENSEMBL  \
27    74747   ENSMUST00000020308.5          -1026  ENSMUSG00000020108
86    76722   ENSMUST00000022122.4        -121087  ENSMUSG00000021622
94    74551   ENSMUST00000048781.4           -102  ENSMUSG00000040618
135  107272  ENSMUST00000025542.10            -69  ENSMUSG00000024640
136   22359   ENSMUST00000164746.8           -190  ENSMUSG00000024924
143   14585   ENSMUST00000131877.2         -26298  ENSMUSG00000025089
156   69065   ENSMUST00000028780.4           -112  ENSMUSG00000027313
170   26570   ENSMUST00000194462.6              0  ENSMUSG00000027737
201   12452   ENSMUST00000149329.2          20937  ENSMUSG00000029385
206  100705   ENSMUST00000146841.2          -2746  ENSMUSG00000042010
214   11987  ENSMUST00000048116.15         -19324  ENSMUSG00000041313
215   27053  ENSMUST00000031766.12             21  ENSMUSG00000029752
251   13685   ENSMUST00000033880.7            900  ENSMUSG00000031490
262   20539   ENSMUST00000183015.2          -2020  ENSMUSG00000040010
267   12306  ENSMUST00000034756.15         -10352  ENSMUSG00000032231

       SYMBOL                                           GENENAME
27      Ddit4                  DNA-damage-inducible transcript 4
86      Ckmt2                   creatine kinase, mitochondrial 2
94       Pck2  phosphoenolpyruvate carboxykinase 2 (mitochond...
135     Psat1                   phosphoserine aminotransferase 1
136     Vldlr              very low density lipoprotein receptor
143     Gfra1  glial cell line derived neurotrophic factor fa...
156     Chac1                 ChaC, cation transport regulator 1
170   Slc7a11  solute carrier family 7 (cationic amino acid t...
201     Ccng2                                          cyclin G2
206     Acacb                 acetyl-Coenzyme A carboxylase beta
214    Slc7a1  solute carrier family 7 (cationic amino acid t...
215      Asns                              asparagine synthetase
251  Eif4ebp1  eukaryotic translation initiation factor 4E bi...
262    Slc7a5  solute carrier family 7 (cationic amino acid t...
267     Anxa2                                         annexin A2

[15 rows x 24 columns]

In [53]:
filtered_genes_new.to_csv('/projectnb/perissilab/Jawahar/GPS2_ChIPseq_Perissi-Lab/Treatment/ATF4/results/annotation/ATF4_ISRpeaks_from_mTORC1_ATF4-TT.bed', sep = '\t')

In [1]:
import pandas as pd
a = pd.read_table('Treatment/ATF4/results/annotation/ATF4_WTpeaks_from_mTORC1_ATF4-IR.bed')
a

,7,chr1,4919686,4919961,276,*,ATF4_WT_peak_14,1142,.,40.3519,...,4928037,4968128,40092,1.1,21399,ENSMUST00000081551.14,-8076,ENSMUSG00000033813,Tcea1,transcription elongation factor A (SII) 1
0,8,chr1,4923863,4923933,71,*,ATF4_WT_peak_15,81,.,7.34146,...,4928037,4968128,40092,1,21399,ENSMUST00000081551.14,-4104,ENSMUSG00000033813,Tcea1,transcription elongation factor A (SII) 1
1,9,chr1,4929377,4929561,185,*,ATF4_WT_peak_16,615,.,24.30200,...,4928261,4968132,39872,1,21399,ENSMUST00000165720.3,1116,ENSMUSG00000033813,Tcea1,transcription elongation factor A (SII) 1
2,10,chr1,4931572,4931847,276,*,ATF4_WT_peak_17,576,.,23.46770,...,4928261,4968132,39872,1,21399,ENSMUST00000165720.3,3311,ENSMUSG00000033813,Tcea1,transcription elongation factor A (SII) 1
3,314,chr1,55125636,55125828,193,*,ATF4_WT_peak_323,317,.,13.16870,...,55116994,55127183,10190,2,15510,ENSMUST00000027123.15,1355,ENSMUSG00000025980,Hspd1,heat shock protein 1 (chaperonin)
4,315,chr1,55126734,55126843,110,*,ATF4_WT_peak_324,85,.,6.84712,...,55116994,55127183,10190,2,15510,ENSMUST00000027123.15,340,ENSMUSG00000025980,Hspd1,heat shock protein 1 (chaperonin)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,19628,chr9,58414598,58414690,93,*,ATF4_WT_peak_20003,108,.,7.10064,...,58396891,58407063,10173,1,319477,ENSMUST00000216294.2,17707,ENSMUSG00000066607,Insyn1,inhibitory synaptic factor 1
171,19692,chr9,62060527,62060732,206,*,ATF4_WT_peak_20067,344,.,10.42620,...,61977750,62029937,52188,2,93683,ENSMUST00000185873.2,-30590,ENSMUSG00000032252,Glce,glucuronyl C5-epimerase
172,20219,chr9,122966220,122966308,89,*,ATF4_WT_peak_20614,70,.,6.20946,...,122956510,122965192,8683,1,66446,ENSMUST00000214741.2,9710,ENSMUSG00000025785,Exosc7,exosome component 7
173,20220,chr9,122966502,122966584,83,*,ATF4_WT_peak_20615,60,.,5.34615,...,122956510,122965192,8683,1,66446,ENSMUST00000214741.2,9992,ENSMUSG00000025785,Exosc7,exosome component 7
174,20363,chrX,70616895,70616998,104,*,ATF4_WT_peak_20760,108,.,8.34033,...,70601389,70603379,1991,1,15354,ENSMUST00000132145.2,15506,ENSMUSG00000015217,Hmgb3,high mobility group box 3

In [12]:
a_1 = a.iloc[:,1:]
a_1.to_csv('Treatment/ATF4/results/annotation/ATF4_WTpeaks_from_mTORC1_ATF4-IR_M.bed', sep = '\t', index=False)

In [14]:
a_1

,chr1,4919686,4919961,276,*,ATF4_WT_peak_14,1142,.,40.3519,119.284,...,4928037,4968128,40092,1.1,21399,ENSMUST00000081551.14,-8076,ENSMUSG00000033813,Tcea1,transcription elongation factor A (SII) 1
0,chr1,4923863,4923933,71,*,ATF4_WT_peak_15,81,.,7.34146,11.46080,...,4928037,4968128,40092,1,21399,ENSMUST00000081551.14,-4104,ENSMUSG00000033813,Tcea1,transcription elongation factor A (SII) 1
1,chr1,4929377,4929561,185,*,ATF4_WT_peak_16,615,.,24.30200,65.81480,...,4928261,4968132,39872,1,21399,ENSMUST00000165720.3,1116,ENSMUSG00000033813,Tcea1,transcription elongation factor A (SII) 1
2,chr1,4931572,4931847,276,*,ATF4_WT_peak_17,576,.,23.46770,61.80340,...,4928261,4968132,39872,1,21399,ENSMUST00000165720.3,3311,ENSMUSG00000033813,Tcea1,transcription elongation factor A (SII) 1
3,chr1,55125636,55125828,193,*,ATF4_WT_peak_323,317,.,13.16870,35.51260,...,55116994,55127183,10190,2,15510,ENSMUST00000027123.15,1355,ENSMUSG00000025980,Hspd1,heat shock protein 1 (chaperonin)
4,chr1,55126734,55126843,110,*,ATF4_WT_peak_324,85,.,6.84712,11.89760,...,55116994,55127183,10190,2,15510,ENSMUST00000027123.15,340,ENSMUSG00000025980,Hspd1,heat shock protein 1 (chaperonin)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,chr9,58414598,58414690,93,*,ATF4_WT_peak_20003,108,.,7.10064,14.21410,...,58396891,58407063,10173,1,319477,ENSMUST00000216294.2,17707,ENSMUSG00000066607,Insyn1,inhibitory synaptic factor 1
171,chr9,62060527,62060732,206,*,ATF4_WT_peak_20067,344,.,10.42620,38.30270,...,61977750,62029937,52188,2,93683,ENSMUST00000185873.2,-30590,ENSMUSG00000032252,Glce,glucuronyl C5-epimerase
172,chr9,122966220,122966308,89,*,ATF4_WT_peak_20614,70,.,6.20946,10.31160,...,122956510,122965192,8683,1,66446,ENSMUST00000214741.2,9710,ENSMUSG00000025785,Exosc7,exosome component 7
173,chr9,122966502,122966584,83,*,ATF4_WT_peak_20615,60,.,5.34615,9.31879,...,122956510,122965192,8683,1,66446,ENSMUST00000214741.2,9992,ENSMUSG00000025785,Exosc7,exosome component 7
174,chrX,70616895,70616998,104,*,ATF4_WT_peak_20760,108,.,8.34033,14.25410,...,70601389,70603379,1991,1,15354,ENSMUST00000132145.2,15506,ENSMUSG00000015217,Hmgb3,high mobility group box 3

In [10]:
atf4_tuni = pd.read_table('ATF4_Publicdata/ATF4_insulin_Rapamycin.txt')
atf4_tuni

     Unnamed: 0               genes   Symbol  entrez     logFC     adj.P.Val
0             1  ENSMUSG00000024359    Hspa9   15526 -0.071599  3.579839e-01
1             2  ENSMUSG00000026456   Cyb5r1   72017 -0.223558  4.578298e-02
2             3  ENSMUSG00000023883    Phf10   72057 -0.007964  9.520628e-01
3             4  ENSMUSG00000039518     Cdsn  386463 -0.307763  1.333633e-01
4             5  ENSMUSG00000025403    Shmt2  108037 -0.230471  7.143343e-02
..          ...                 ...      ...     ...       ...           ...
107         108  ENSMUSG00000046516    Cox17   12856 -0.260391  1.977019e-01
108         109  ENSMUSG00000026275   Ppp1r7   66385  0.030580  7.944266e-01
109         110  ENSMUSG00000071359    Tbpl1  237336  0.123369  2.335729e-01
110         111  ENSMUSG00000025993  Slc40a1   53945  0.277958  5.917686e-01
111         112  ENSMUSG00000047139    Cd24a   12484  0.612392  8.503610e-07

[112 rows x 6 columns]

In [11]:
atf4_tuni['Symbol']

0        Hspa9
1       Cyb5r1
2        Phf10
3         Cdsn
4        Shmt2
        ...
107      Cox17
108     Ppp1r7
109      Tbpl1
110    Slc40a1
111      Cd24a
Name: Symbol, Length: 112, dtype: object

In [12]:
filtered_genes_new = atf4_isr[atf4_isr['SYMBOL'].isin(atf4_tuni['Symbol'])]
filtered_genes_new

,seqnames,start,end,width,strand,V4,V5,V6,V7,V8,...,geneStart,geneEnd,geneLength,geneStrand,geneId,transcriptId,distanceToTSS,ENSEMBL,SYMBOL,GENENAME
27,chr10,59788682,59788719,38,*,ATF4_ISR_peak_255,42,.,6.19749,8.83817,...,59785491,59787656,2166,2,74747,ENSMUST00000020308.5,-1026,ENSMUSG00000020108,Ddit4,DNA-damage-inducible transcript 4
38,chr10,127357724,127357909,186,*,ATF4_ISR_peak_272,69,.,7.55192,11.67470,...,127356337,127358233,1897,2,108037,ENSMUST00000217682.2,324,ENSMUSG00000025403,Shmt2,serine hydroxymethyltransferase 2 (mitochondrial)
68,chr12,84034236,84034383,148,*,ATF4_ISR_peak_336,162,.,11.89690,21.23510,...,84034635,84040647,6013,1,171210,ENSMUST00000021649.8,-252,ENSMUSG00000021226,Acot2,acyl-CoA thioesterase 2
94,chr14,55777565,55777621,57,*,ATF4_ISR_peak_431,44,.,6.26331,9.03793,...,55777723,55787474,9752,1,74551,ENSMUST00000048781.4,-102,ENSMUSG00000040618,Pck2,phosphoenolpyruvate carboxykinase 2 (mitochond...
135,chr19,15902492,15902540,49,*,ATF4_ISR_peak_571,47,.,6.44745,9.36532,...,15882042,15902423,20382,2,107272,ENSMUST00000025542.10,-69,ENSMUSG00000024640,Psat1,phosphoserine aminotransferase 1
136,chr19,27194191,27194230,40,*,ATF4_ISR_peak_573,69,.,7.55192,11.67470,...,27194420,27212256,17837,1,22359,ENSMUST00000164746.8,-190,ENSMUSG00000024924,Vldlr,very low density lipoprotein receptor
156,chr2,119181433,119181598,166,*,ATF4_ISR_peak_624,179,.,11.61380,23.01790,...,119181710,119184862,3153,1,69065,ENSMUST00000028780.4,-112,ENSMUSG00000027313,Chac1,"ChaC, cation transport regulator 1"
170,chr3,50398041,50398095,55,*,ATF4_ISR_peak_668,28,.,5.39310,7.39269,...,49846975,50398063,551089,2,26570,ENSMUST00000194462.6,0,ENSMUSG00000027737,Slc7a11,solute carrier family 7 (cationic amino acid t...
214,chr5,148356038,148356122,85,*,ATF4_ISR_peak_780,105,.,9.34704,15.38320,...,148264220,148336714,72495,2,11987,ENSMUST00000048116.15,-19324,ENSMUSG00000041313,Slc7a1,solute carrier family 7 (cationic amino acid t...
215,chr6,7693191,7693233,43,*,ATF4_ISR_peak_789,89,.,8.46638,13.79060,...,7675169,7693254,18086,2,27053,ENSMUST00000031766.12,21,ENSMUSG00000029752,Asns,asparagine synthetase
224,chr6,83294122,83294161,40,*,ATF4_ISR_peak_810,67,.,7.42758,11.45510,...,83283384,83294535,11152,2,17768,ENSMUST00000203847.3,374,ENSMUSG00000005667,Mthfd2,methylenetetrahydrofolate dehydrogenase (NAD+ ...
225,chr6,83294224,83294261,38,*,ATF4_ISR_peak_811,67,.,7.46269,11.51680,...,83283384,83294535,11152,2,17768,ENSMUST00000203847.3,274,ENSMUSG00000005667,Mthfd2,methylenetetrahydrofolate dehydrogenase (NAD+ ...
251,chr8,27751257,27751325,69,*,ATF4_ISR_peak_856,60,.,7.10962,10.69900,...,27750357,27766702,16346,1,13685,ENSMUST00000033880.7,900,ENSMUSG00000031490,Eif4ebp1,eukaryotic translation initiation factor 4E bi...
260,chr8,111760337,111760381,45,*,ATF4_ISR_peak_870,24,.,5.20901,6.97971,...,111760511,111771756,11246,1,234734,ENSMUST00000154546.8,-130,ENSMUSG00000031960,Aars,alanyl-tRNA synthetase
262,chr8,122625261,122625408,148,*,ATF4_ISR_peak_873,66,.,7.41015,11.42460,...,122615113,122623241,8129,2,20539,ENSMUST00000183015.2,-2020,ENSMUSG00000040010,Slc7a5,solute carrier family 7 (cationic amino acid t...

In [8]:
filtered_genes_new.to_csv('/projectnb/perissilab/Jawahar/GPS2_ChIPseq_Perissi-Lab/Treatment/ATF4/results/annotation/ATF4_ISRpeaks_from_mTORC1_ATF4-IR.bed', sep = '\t')

In [11]:
filtered_genes_new['SYMBOL'].to_csv('Gene_Names.txt', sep = '\t')